name: project-feanor-mvp-pipeline

on:
  push:
    branches:
      - CICD-updates
  pull_request:
    branches:
      - main

jobs:
  run-tests:

    name: run-tests
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2
      AWS_DEFAULT_REGION: eu-west-2

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Requirements
        run: make requirements
      - name: Dev setup
        run: make dev-setup
      - name: Run checks
        run: make run-checks

  deploy-terraform:
    
    name: deploy-terraform
    runs-on: ubuntu-latest
    needs: run-tests
    environment: dev
    steps:
      - name: Checkout  repo
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: setup aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
      - name: terraform init
        working-directory: terraform
        run: terraform init
      - name: terraform plan
        working-directory: terraform
        run: terraform plan
      - name: terraform format
        working-directory: terraform
        run: terraform fmt
      - name: terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve
      